import numpy as np

time_steps = 100
input_features = 32
output_features = 64

inputs = np.random.random((time_steps, input_features)) # input data generated by random

state_t = np.zeros((output_features,))

W = np.random.random((output_features, input_features))

U = np.random.random((output_features, output_features))

b = np.random.random((output_features,))

successive_outputs = []

for input_t in inputs:
    output_t = np.tanh(np.dot(W, input_t) + np.dot(U, state_t) + b)

    successive_outputs.append(output_t)

    state_t = output_t

print(len(successive_outputs)) # length is equal to time steps
output_sequence = np.stack(successive_outputs, axis=0) # axis=0 -> x-axis

print(output_sequence.shape) # (100, 64) -> (time_steps, output_features)